export const Users = [
    {
        id: 1,
        profilePicture: "person/1.jpg",
        username: "Lana Rhoades",
    },
    {
        id: 2,
        profilePicture: "person/2.jpg",
        username: "Eva Elfie",
    },
    {
        id: 3,
        profilePicture: "person/3.jpg",
        username: "Lexi Lore",
    },
    {
        id: 4,
        profilePicture: "person/4.jpg",
        username: "Blair Williams",
    },
    {
        id: 5,
        profilePicture: "person/5.jpg",
        username: "Emily Wilis",
    },
    {
        id: 6,
        profilePicture: "person/6.jpg",
        username: "Gabbie Carter",
    },
    {
        id: 7,
        profilePicture: "person/7.jpg",
        username: "Kimmy Granger",
    },
    {
        id: 8,
        profilePicture: "person/8.jpg",
        username: "Elsa Jean",
    },
    {
        id: 9,
        profilePicture: "person/9.jpg",
        username: "Eliza Ibarra",
    },
    {
        id: 10,
        profilePicture: "person/10.jpg",
        username: "Emily Grey",
    },
    {
        id: 11,
        profilePicture: "person/11.jpg",
        username: "Liya Silver",
    }
];

export const Posts = [
    {
        id: 1,
        desc: "#FeelingFresh",
        photo: "person/3.jpg",
        date: "5 mins ago",
        userId: 3,
        like: 734,
        comment: 129,
    },
    {
        id: 2,
        photo: "post/2.jpeg",
        date: "15 mins ago",
        userId: 2,
        like: 2,
        comment: 1,
    },
    {
        id: 3,
        desc: "Every moment is a fresh beginning.",
        photo: "post/3.jpeg",
        date: "1 hour ago",
        userId: 3,
        like: 61,
        comment: 2,
    },
    {
        id: 4,
        photo: "post/4.jpeg",
        date: "4 hours ago",
        userId: 4,
        like: 7,
        comment: 3,
    },
    {
        id: 5,
        photo: "post/5.jpeg",
        date: "5 hours ago",
        userId: 5,
        like: 23,
        comment: 5,
    },
    {
        id: 6,
        photo: "post/6.jpeg",
        date: "1 day ago",
        userId: 6,
        like: 44,
        comment: 6,
    },
    {
        id: 7,
        desc: "Never regret anything that made you smile.",
        photo: "post/7.jpeg",
        date: "2 days ago",
        userId: 7,
        like: 52,
        comment: 3,
    },
    {
        id: 8,
        photo: "post/8.jpeg",
        date: "3 days ago",
        userId: 8,
        like: 15,
        comment: 1,
    },
    {
        id: 9,
        desc: "Change the world by being yourself.",
        photo: "post/9.jpeg",
        date: "5 days ago",
        userId: 9,
        like: 11,
        comment: 2,
    },
    {
        id: 10,
        photo: "post/10.jpeg",
        date: "1 week ago",
        userId: 10,
        like: 104,
        comment: 12,
    },
];